//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soko.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soko.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B0000, Vehicle speed information circuit malfunction
        ///B0001, PCM Discrete Input Speed Signal Error
        ///B0001, PCM Discrete Input Speed Signal Error
        ///B0002, Vehicle speed information circuit low
        ///B0002, Vehicle speed information circuit low
        ///B0003, Vehicle speed information circuit high
        ///B0003, Vehicle speed information circuit high
        ///B0004, PCM Discrete Input Speed Signal Not Present
        ///B0004, PCM Discrete Input Speed Signal Not Present
        ///B0005, In Park Switch Circuit Malfunction
        ///B0005, In Park Switch Circuit Malfunction
        ///B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTC_GM {
            get {
                return ResourceManager.GetString("DTC_GM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LinearGauge2_Back {
            get {
                object obj = ResourceManager.GetObject("LinearGauge2_Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LinearGauge2_Back_H {
            get {
                object obj = ResourceManager.GetObject("LinearGauge2_Back_H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LinearGauge2_Front {
            get {
                object obj = ResourceManager.GetObject("LinearGauge2_Front", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LinearGauge2_Front_H {
            get {
                object obj = ResourceManager.GetObject("LinearGauge2_Front_H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LinearGaugeProgress {
            get {
                object obj = ResourceManager.GetObject("LinearGaugeProgress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MessageBox_critical {
            get {
                object obj = ResourceManager.GetObject("MessageBox_critical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MessageBox_information {
            get {
                object obj = ResourceManager.GetObject("MessageBox_information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MessageBox_question {
            get {
                object obj = ResourceManager.GetObject("MessageBox_question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MessageBox_warning {
            get {
                object obj = ResourceManager.GetObject("MessageBox_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceButton_DefaultIcon {
            get {
                object obj = ResourceManager.GetObject("NiceButton_DefaultIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceButton_DefaultIconInactive {
            get {
                object obj = ResourceManager.GetObject("NiceButton_DefaultIconInactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceIndicator_DefaultIcon {
            get {
                object obj = ResourceManager.GetObject("NiceIndicator_DefaultIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_down_arrow {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_down_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_down_arrow_BLACK {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_down_arrow_BLACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_down_arrow_BLUE {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_down_arrow_BLUE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_down_arrow_clicked {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_down_arrow_clicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_down_arrow_clicked_BLACK {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_down_arrow_clicked_BLACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_down_arrow_clicked_BLUE {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_down_arrow_clicked_BLUE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_down_arrow_clicked_SILVER {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_down_arrow_clicked_SILVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_down_arrow_over {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_down_arrow_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_down_arrow_over_BLACK {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_down_arrow_over_BLACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_down_arrow_over_BLUE {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_down_arrow_over_BLUE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_down_arrow_over_SILVER {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_down_arrow_over_SILVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_down_arrow_SILVER {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_down_arrow_SILVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_scroll_bgnd {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_scroll_bgnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_scroll_button {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_scroll_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_scroll_button_clicked {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_scroll_button_clicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_scroll_button_over {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_scroll_button_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_up_arrow {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_up_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_up_arrow_BLACK {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_up_arrow_BLACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_up_arrow_BLUE {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_up_arrow_BLUE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_up_arrow_clicked {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_up_arrow_clicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_up_arrow_clicked_BLACK {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_up_arrow_clicked_BLACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_up_arrow_clicked_BLUE {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_up_arrow_clicked_BLUE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_up_arrow_clicked_SILVER {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_up_arrow_clicked_SILVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_up_arrow_over {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_up_arrow_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_up_arrow_over_BLACK {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_up_arrow_over_BLACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_up_arrow_over_BLUE {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_up_arrow_over_BLUE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_up_arrow_over_SILVER {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_up_arrow_over_SILVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NiceScrollbar_up_arrow_SILVER {
            get {
                object obj = ResourceManager.GetObject("NiceScrollbar_up_arrow_SILVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
