//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GST.Gearshift.Components.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GST.Gearshift.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogInputChannelConfigPanel_Add_32x32 {
            get {
                object obj = ResourceManager.GetObject("AnalogInputChannelConfigPanel_Add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogInputChannelConfigPanel_Add_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("AnalogInputChannelConfigPanel_Add_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogInputChannelConfigPanel_Cancel_32x32 {
            get {
                object obj = ResourceManager.GetObject("AnalogInputChannelConfigPanel_Cancel_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogInputChannelConfigPanel_Cancel_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("AnalogInputChannelConfigPanel_Cancel_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogInputChannelConfigPanel_Check_32x32 {
            get {
                object obj = ResourceManager.GetObject("AnalogInputChannelConfigPanel_Check_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogInputChannelConfigPanel_Check_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("AnalogInputChannelConfigPanel_Check_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogInputChannelConfigPanel_Delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("AnalogInputChannelConfigPanel_Delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogInputChannelConfigPanel_Delete_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("AnalogInputChannelConfigPanel_Delete_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogInputChannelConfigPanel_Minus_32x32 {
            get {
                object obj = ResourceManager.GetObject("AnalogInputChannelConfigPanel_Minus_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogOutputsPanel_Calibration_64x64 {
            get {
                object obj = ResourceManager.GetObject("AnalogOutputsPanel_Calibration_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogOutputsPanel_clean {
            get {
                object obj = ResourceManager.GetObject("AnalogOutputsPanel_clean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AO_Calibration_96 {
            get {
                object obj = ResourceManager.GetObject("AO-Calibration-96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap App_icon_96 {
            get {
                object obj = ResourceManager.GetObject("App-icon-96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueReachOfficial_297x56 {
            get {
                object obj = ResourceManager.GetObject("BlueReachOfficial_297x56", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BluereachReportLogo {
            get {
                object obj = ResourceManager.GetObject("BluereachReportLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BR_LOGO_SOLTEST {
            get {
                object obj = ResourceManager.GetObject("BR_LOGO_SOLTEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BR_LOGO2_SOLTEST {
            get {
                object obj = ResourceManager.GetObject("BR_LOGO2_SOLTEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Can_Bus_Utility_96 {
            get {
                object obj = ResourceManager.GetObject("Can-Bus-Utility-96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel_64x64 {
            get {
                object obj = ResourceManager.GetObject("Cancel_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_btn_OFF_orange {
            get {
                object obj = ResourceManager.GetObject("CanPanel_btn_OFF_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_btn_ON_orange {
            get {
                object obj = ResourceManager.GetObject("CanPanel_btn_ON_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_CAN_OFF_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_CAN_OFF_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_CAN_OFF_BW_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_CAN_OFF_BW_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_CAN_ON_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_CAN_ON_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_CAN_ON_BW_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_CAN_ON_BW_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_file_save {
            get {
                object obj = ResourceManager.GetObject("CanPanel_file_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Gnome_Media_Playback_Start_48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Gnome_Media_Playback_Start_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Gnome_Media_Playback_Stop_48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Gnome_Media_Playback_Stop_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Gnome_Media_Record_48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Gnome_Media_Record_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Gnome_Media_Record_BW_48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Gnome_Media_Record_BW_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Gnome_Media_Record_BW_Light_48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Gnome_Media_Record_BW_Light_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_NewConfig_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_NewConfig_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Play_32x32 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Play_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Play_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Play_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Play_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Play_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Play_BW_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Play_BW_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_ResetSniffer_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_ResetSniffer_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_ResetSniffer_BW_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_ResetSniffer_BW_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Stock_Index_Down_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Stock_Index_Down_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Stock_Index_Up_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Stock_Index_Up_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Stop_32x32 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Stop_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Stop_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Stop_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Stop_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Stop_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_Stop_BW_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_Stop_BW_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_TRM_DSBLD_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_TRM_DSBLD_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanPanel_TRM_ENBLD_48x48 {
            get {
                object obj = ResourceManager.GetObject("CanPanel_TRM_ENBLD_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Configure_48x48 {
            get {
                object obj = ResourceManager.GetObject("Configure_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Continue_64x64 {
            get {
                object obj = ResourceManager.GetObject("Continue_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Continue_BW_64x64 {
            get {
                object obj = ResourceManager.GetObject("Continue_BW_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ControlPanel_AutoMode_96x96 {
            get {
                object obj = ResourceManager.GetObject("ControlPanel_AutoMode_96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ControlPanel_Down_icon_64 {
            get {
                object obj = ResourceManager.GetObject("ControlPanel_Down_icon_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ControlPanel_Down_icon_BW_64 {
            get {
                object obj = ResourceManager.GetObject("ControlPanel_Down_icon_BW_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ControlPanel_Idle_96x96 {
            get {
                object obj = ResourceManager.GetObject("ControlPanel_Idle_96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ControlPanel_Initial_96x96 {
            get {
                object obj = ResourceManager.GetObject("ControlPanel_Initial_96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ControlPanel_LoopMode_96x96 {
            get {
                object obj = ResourceManager.GetObject("ControlPanel_LoopMode_96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ControlPanel_ManualMode_96x96 {
            get {
                object obj = ResourceManager.GetObject("ControlPanel_ManualMode_96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ControlPanel_Stop_icon_64 {
            get {
                object obj = ResourceManager.GetObject("ControlPanel_Stop_icon_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ControlPanel_Stop_icon_64_BW {
            get {
                object obj = ResourceManager.GetObject("ControlPanel_Stop_icon_64_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ControlPanel_Stopped_96x96 {
            get {
                object obj = ResourceManager.GetObject("ControlPanel_Stopped_96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ControlPanel_Up_icon_64 {
            get {
                object obj = ResourceManager.GetObject("ControlPanel_Up_icon_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ControlPanel_Up_icon_BW_64 {
            get {
                object obj = ResourceManager.GetObject("ControlPanel_Up_icon_BW_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CrackCode_48x48 {
            get {
                object obj = ResourceManager.GetObject("CrackCode_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CurrentSenseChannelConfigPanel_Add_32x32 {
            get {
                object obj = ResourceManager.GetObject("CurrentSenseChannelConfigPanel_Add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CurrentSenseChannelConfigPanel_Add_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("CurrentSenseChannelConfigPanel_Add_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CurrentSenseChannelConfigPanel_Cancel_32x32 {
            get {
                object obj = ResourceManager.GetObject("CurrentSenseChannelConfigPanel_Cancel_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CurrentSenseChannelConfigPanel_Cancel_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("CurrentSenseChannelConfigPanel_Cancel_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CurrentSenseChannelConfigPanel_Check_32x32 {
            get {
                object obj = ResourceManager.GetObject("CurrentSenseChannelConfigPanel_Check_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CurrentSenseChannelConfigPanel_Check_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("CurrentSenseChannelConfigPanel_Check_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CurrentSenseChannelConfigPanel_Delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("CurrentSenseChannelConfigPanel_Delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CurrentSenseChannelConfigPanel_Delete_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("CurrentSenseChannelConfigPanel_Delete_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit_96 {
            get {
                object obj = ResourceManager.GetObject("Exit-96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EZS_LOGO_SOLTEST {
            get {
                object obj = ResourceManager.GetObject("EZS_LOGO_SOLTEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FirmwareUpdateForm_Chip_256x256 {
            get {
                object obj = ResourceManager.GetObject("FirmwareUpdateForm_Chip_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FirmwareUpdateForm_Start_128x128 {
            get {
                object obj = ResourceManager.GetObject("FirmwareUpdateForm_Start_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FirmwareUpdateForm_ThumbsUp_256x256 {
            get {
                object obj = ResourceManager.GetObject("FirmwareUpdateForm_ThumbsUp_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FirmwareUpdateForm_Warning_256x256 {
            get {
                object obj = ResourceManager.GetObject("FirmwareUpdateForm_Warning_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FirmwareUpdateForm_Warning_256x2561 {
            get {
                object obj = ResourceManager.GetObject("FirmwareUpdateForm_Warning_256x2561", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GearboxConfigPanel_EmptyPage_48 {
            get {
                object obj = ResourceManager.GetObject("GearboxConfigPanel_EmptyPage_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GearboxConfigPanel_Export_48 {
            get {
                object obj = ResourceManager.GetObject("GearboxConfigPanel_Export_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GearboxConfigPanel_Import_48 {
            get {
                object obj = ResourceManager.GetObject("GearboxConfigPanel_Import_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GearboxScaled {
            get {
                object obj = ResourceManager.GetObject("GearboxScaled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Graph_96 {
            get {
                object obj = ResourceManager.GetObject("Graph-96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GST_ReportLogo {
            get {
                object obj = ResourceManager.GetObject("GST_ReportLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gstDarkBG {
            get {
                object obj = ResourceManager.GetObject("gstDarkBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gstLogo {
            get {
                object obj = ResourceManager.GetObject("gstLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeScreenPanel_AOCalibration {
            get {
                object obj = ResourceManager.GetObject("HomeScreenPanel_AOCalibration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeScreenPanel_back {
            get {
                object obj = ResourceManager.GetObject("HomeScreenPanel_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeScreenPanel_BRLogo {
            get {
                object obj = ResourceManager.GetObject("HomeScreenPanel_BRLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeScreenPanel_canbusUtils {
            get {
                object obj = ResourceManager.GetObject("HomeScreenPanel_canbusUtils", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeScreenPanel_exit {
            get {
                object obj = ResourceManager.GetObject("HomeScreenPanel_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeScreenPanel_EZSLogo {
            get {
                object obj = ResourceManager.GetObject("HomeScreenPanel_EZSLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeScreenPanel_forward {
            get {
                object obj = ResourceManager.GetObject("HomeScreenPanel_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeScreenPanel_installTests {
            get {
                object obj = ResourceManager.GetObject("HomeScreenPanel_installTests", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeScreenPanel_reports {
            get {
                object obj = ResourceManager.GetObject("HomeScreenPanel_reports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeScreenPanel_searchBox {
            get {
                object obj = ResourceManager.GetObject("HomeScreenPanel_searchBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeScreenPanel_SUPPORT {
            get {
                object obj = ResourceManager.GetObject("HomeScreenPanel_SUPPORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeScreenPanel_systemOptions {
            get {
                object obj = ResourceManager.GetObject("HomeScreenPanel_systemOptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeScreenPanel_TestManager {
            get {
                object obj = ResourceManager.GetObject("HomeScreenPanel_TestManager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestChannel_Check_32x32 {
            get {
                object obj = ResourceManager.GetObject("InitialTestChannel_Check_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestChannel_Delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("InitialTestChannel_Delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestChannel_Navigate_Down_20x14 {
            get {
                object obj = ResourceManager.GetObject("InitialTestChannel_Navigate_Down_20x14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestChannel_Navigate_Up_20x14 {
            get {
                object obj = ResourceManager.GetObject("InitialTestChannel_Navigate_Up_20x14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_ArrowRight_128x128 {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_ArrowRight_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_AutoMode_96x96 {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_AutoMode_96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_Delete_48x48 {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_Delete_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_Delete_48x48_BW {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_Delete_48x48_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_Gears_128x128 {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_Gears_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_LoopMode_96x96 {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_LoopMode_96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_manual {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_manual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_ManualMode_96x96 {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_ManualMode_96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_navigateRight_128x128 {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_navigateRight_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_navigateRight_64x64 {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_navigateRight_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_Refresh_48 {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_Refresh_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_Services_48x48 {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_Services_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_Stop_128x128 {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_Stop_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_Stop_96x96 {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_Stop_96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitialTestPanel_Stopped_96x96 {
            get {
                object obj = ResourceManager.GetObject("InitialTestPanel_Stopped_96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LivePreviewPanel_Pause_16x16 {
            get {
                object obj = ResourceManager.GetObject("LivePreviewPanel_Pause_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LivePreviewPanel_Pause_16x16_BW {
            get {
                object obj = ResourceManager.GetObject("LivePreviewPanel_Pause_16x16_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LivePreviewPanel_Play_16x16 {
            get {
                object obj = ResourceManager.GetObject("LivePreviewPanel_Play_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LivePreviewPanel_Play_16x16_BW {
            get {
                object obj = ResourceManager.GetObject("LivePreviewPanel_Play_16x16_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LivePreviewPanel_Stop_16x16 {
            get {
                object obj = ResourceManager.GetObject("LivePreviewPanel_Stop_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LivePreviewPanel_Stop_16x16_BW {
            get {
                object obj = ResourceManager.GetObject("LivePreviewPanel_Stop_16x16_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_btn_OFF_orange {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_btn_OFF_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_btn_ON {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_btn_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_btn_ON_green {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_btn_ON_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_btn_ON_orange {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_btn_ON_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_CAR_48x48 {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_CAR_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_CAR_48x48_BW {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_CAR_48x48_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_ClearDTCs_48x48 {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_ClearDTCs_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_ClearDTCs_48x48_BW {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_ClearDTCs_48x48_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_Delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_Delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_DL_48x48 {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_DL_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_DL_48x48_BW {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_DL_48x48_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_messagebox_warning_48 {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_messagebox_warning_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_MIL_48x36 {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_MIL_48x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_MIL_48x36_BW {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_MIL_48x36_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_MIL2 {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_MIL2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_MIL2_BW {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_MIL2_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_OBD2CON_48x48 {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_OBD2CON_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_OBD2CON_48x48_DSBLD {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_OBD2CON_48x48_DSBLD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_Play_32x32 {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_Play_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_Play_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_Play_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_Stop_32x32 {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_Stop_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ObdPanel_Stop_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("ObdPanel_Stop_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PTL_LOGO_SOLTEST {
            get {
                object obj = ResourceManager.GetObject("PTL_LOGO_SOLTEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QUIT_BTN_SOLTEST {
            get {
                object obj = ResourceManager.GetObject("QUIT_BTN_SOLTEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Report_96 {
            get {
                object obj = ResourceManager.GetObject("Report-96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REPORTS_BTN_SOLTEST {
            get {
                object obj = ResourceManager.GetObject("REPORTS_BTN_SOLTEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_application_table {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_application_table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_button_cancel_48x48 {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_button_cancel_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_check {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_currents_32x32 {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_currents_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_Empty_Page_32x32 {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_Empty_Page_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_filesave_32x32 {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_filesave_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_get_info1 {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_get_info1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_info {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_printer_off {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_printer_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_printer_paper_256x256 {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_printer_paper_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_quick_restart {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_quick_restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_Refresh_32 {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_Refresh_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_rename_32x32 {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_rename_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportViewerPanel_Save_48x48 {
            get {
                object obj = ResourceManager.GetObject("ReportViewerPanel_Save_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Setting_96 {
            get {
                object obj = ResourceManager.GetObject("Setting-96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsEditor_add_user_64x64 {
            get {
                object obj = ResourceManager.GetObject("SettingsEditor_add_user_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsEditor_delete_user_64x64 {
            get {
                object obj = ResourceManager.GetObject("SettingsEditor_delete_user_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsEditor_ResetTimer_64x64 {
            get {
                object obj = ResourceManager.GetObject("SettingsEditor_ResetTimer_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tech_Support_96 {
            get {
                object obj = ResourceManager.GetObject("Tech-Support-96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Test_96 {
            get {
                object obj = ResourceManager.GetObject("Test-96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Test_Manager_96 {
            get {
                object obj = ResourceManager.GetObject("Test-Manager-96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Add_32x32 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Add_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Add_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Cancel_32x32 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Cancel_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Cancel_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Cancel_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Check_32x32 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Check_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Check_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Check_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_copy_32x32 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_copy_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Cut_32x32 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Cut_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Delete_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Delete_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Delete_48x48 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Delete_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Down_32x32 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Down_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Down_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Down_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Empty_Page_32x32 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Empty_Page_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_filesave_32x32 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_filesave_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_paste_32x32 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_paste_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Refresh_32x32 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Refresh_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Save_48x48 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Save_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Up_32x32 {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Up_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestScriptEditorPanel_Up_32x32_BW {
            get {
                object obj = ResourceManager.GetObject("TestScriptEditorPanel_Up_32x32_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Usb_48x48 {
            get {
                object obj = ResourceManager.GetObject("Usb_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Waiting_48x48 {
            get {
                object obj = ResourceManager.GetObject("Waiting_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
